### PR TITLE
Changes to allow hosting dhcp server from command line on windows.

### PR DESCRIPTION
**Pull request by apexearth**
Tried to get things running on my windows machine and hit some roadblocks.
These changes allowed me to get a server running on Windows using the following command-line:

    node bin\dhcp-cli.js 
                         --range 192.168.50.100-192.168.50.199 
                         --hostname xxxxxxxx 
                         --server 192.168.50.1 
                         --router 192.168.50.1 
                         --serve

I had to add `--serve` because windows doesn't seem to receive the args in the same way as osx and linux.

Without the added options I was hitting "Invalid option" errors.

### CODE REVIEW

**Comment by infusion** [comment]
Hi Chris, thanks for the pull request! Before merging, could you do me a favor and show me the 
```
console.log(process.argv)
```
output for both, running "dhcp" and "dhcpd"? That's really unusual, that node makes a different on such a basal feature.

About the second commit, I think about hard-coding the two default values for randomIP and static. What do you think, introducing virtual ID's might confuse in the long run

**Comment by apexearth** [comment]
> About the second commit, I think about hard-coding the two default values for randomIP and static. What do you think, introducing virtual ID's might confuse in the long run

I would defer to your better judgement on this.
I wasn't sure how best to approach the situation, or if they even had any proper IDs.

Here is that output:

```
$ dhcp --range 192.168.50.100-192.168.50.199 --hostname xxxxxxxx --server 192.168.50.1 --router 192.168.50.1 --serve
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\cjacobs\\AppData\\Roaming\\npm\\node_modules\\dhcp\\bin\\dhcp-cli.js',
  '--range',
  '192.168.50.100-192.168.50.199',
  '--hostname',
  'xxxxxxxx',
  '--server',
  '192.168.50.1',
  '--router',
  '192.168.50.1',
  '--serve' ]
```

```
$ dhcpd --range 192.168.50.100-192.168.50.199 --hostname xxxxxxxx --server 192.168.50.1 --router 192.168.50.1 --serve
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\cjacobs\\AppData\\Roaming\\npm\\node_modules\\dhcp\\bin\\dhcp-cli.js',
  '--range',
  '192.168.50.100-192.168.50.199',
  '--hostname',
  'xxxxxxxx',
  '--server',
  '192.168.50.1',
  '--router',
  '192.168.50.1',
  '--serve' ]
```

**Comment by infusion** [comment]
Okay, that's pretty interesting. On OSX, the format is

```
$ dhcpd --range 192.168.50.100-192.168.50.199 --hostname xxxxxxxx --server 192.168.50.1 --router 192.168.50.1 --serve
[ '/usr/local/Cellar/node/8.1.2/bin/node',
  '/usr/local/bin/dhcpd',
  '--range',
  '192.168.50.100-192.168.50.199',
 ...]
```

I'll ask on the node bug tracker, if this behavior is intended. One way to tackle this problem instantly would be to link to two "binary" files, instead of one `dhcp-cli.js`. I'm not in favor of adding an attribute for the sole purpose of distinguishing between the commands.

Another way would be, to remove one command (for example `dhcpd`) and solely use `dhcp`. But I like the two commands-version better. What you think?

**Comment by apexearth** [comment]
You could also separate your bin js files so each bin command calls a separate cli js file. 
They don't have to point to the same thing. They perform totally different actions.

**Comment by infusion** [comment]
Yeah, that's what I meant with " One way to tackle this problem instantly would be to link to two "binary" files, instead of one dhcp-cli.js.". I think this is the best solution for now. Would you change your PR in this direction please? :)

**Comment by infusion** [comment]
Yeah, I like it!

**Pull request merged**
