### PR TITLE
server: expose close

### PR DESCRIPTION
**Pull request by fredericosilva**
Expose socket close and socket.on('close', ..) event on the server

### CODE REVIEW

**Comment by infusion** [comment]
Hmm, shouldn't `close()` be called in the examples? And what about the client?

**Comment by fredericosilva** [comment]
Agree, it might be useful on client as well. 

On the server example we can call it on the `process.on('SIGINT', ...)` ? and on the client after the bound? Any thoughts?

**Comment by infusion** [comment]
Yep, that sounds reasonable, since the client is terminated on bound. Could you add these features to the cli interfaces as well? THX!

**Comment by fredericosilva** [comment]
Done :)

**Comment by infusion** [comment]
That looks good! :) 
A bit off-topic, but could I ask you to have a look at #13?

**Pull request merged**
