### PR TITLE
Use the configured broadcast address instead of INADDR_BROADCAST

### LINKED ISSUE #19: Sending Offer Fails
Thank you so much for creating this amazing package, I have been having fun with it! :)

I have ran into one issue though.. I am trying to get a raspberry pi to broadcast it's own wifi to have an "intranet" of sorts and as such, it is not connected to any other network.

The wifi interface is configured with the following:
```js
{
    interface: 'wlan0',
    ipv4_address: '10.10.10.1',
    ipv4_broadcast: '10.10.10.255',
    ipv4_subnet_mask: '255.255.255.0',
}
```

Here are the options I pass to `dhcp.createServer(dhcpOptions)`.
```js
const dhcpOptions = {
    range: ['10.10.10.1', '10.10.10.100'],
    static: {
        'b8:27:eb:46:50:32': '10.10.10.1'
    },
    netmask: '255.255.255.0',
    router: ['10.10.10.1'],
    dns: [ '4.4.4.4', '8.8.8.8' ],
    server: '10.10.10.1',
    randomIP: false,
};
```

And then here is the error message I am getting:
```
Send Offer
{ Error: send ENETUNREACH 255.255.255.255:68
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:474:11)
  code: 'ENETUNREACH',
  errno: 'ENETUNREACH',
  syscall: 'send',
  address: '255.255.255.255',
  port: 68 }
```

This error comes after it is handling a discovery...I know I am missing some small piece of the puzzle, but I can't figure it out and am wondering if I have maybe misconfigured something. Thanks in advance!

### PR DESCRIPTION
**Pull request by graywolf336**
Closes #19 (see the comments)

### CODE REVIEW

**Comment by infusion** [comment]
Ahh, you "fixed" it for the client as well. The client must send to ANY, since it does not know anything. Only the server can use the interface information.

**Comment by graywolf336** [comment]
Heh, whoops I just did a find and replace. 🙈 One second

**Comment by infusion** [comment]
That looks good :)

**Comment by graywolf336** [comment]
Awesome, thanks for merging! :) Any chance you can do a new release to npm?

**Comment by infusion** [comment]
done ;)

**Comment by graywolf336** [comment]
You're awesome, thank you very much!

**Pull request merged**
